### ISSUE TITLE
Stop cookie banner content appearing in pages Google search description

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/cookie-consent#106]
When searching for the 'NHS digital service manual' on Google, some pages search description returns the content of the cookie banner (as this the first body copy on the page). However it should be returning the description meta data, which each page has. 

We have been advised by an SEO expert that we could try:

> It looks like the cookie banner is regular content (it has a `<h2>` and `<p>` text) that is being inserted using JS for users who haven't yet accepted analytics cookies. 
> 
> Essentially, to search engines, the text forms part of the page, meaning that it can be crawled, indexed and pulled through as "snippets" in the search results (in place of the meta description). In the same way, any message in a banner on the nhs.uk site (currently the heading "Coronavirus (COVID-19)") forms part of the page content – every page has "coronavirus" on it. 
>
> One solution could be to use the `data-nosnippet` tag on the cookie banner, and possibly the yellow banner as well: https://developers.google.com/search/reference/robots_meta_tag#data-nosnippet-attr
> 
> This would mean that Google would not show information from those text snippets in the meta description. 
> 
> Please would you be able to pass on this to the relevant people? I'm happy to chat with them, too. 

Internal JIRA isssue: https://jira.service.nhs.uk/browse/SS-763

**Comment by tomdoughty** [comment]
The above fix would be a good catch all but to me isn't the full point of what has happened. I would argue this is more due to the descriptions set in the Service Manual. If Google do not deem them suitable then they will replace it with content from the page. If the descriptions were written more inline with what Google want then this might be avoided. This will always be an implementation detail for each application using the banner and should be something individual teams are aware of.

When you [search the service manual using a site query](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fservice-manual.nhs.uk%2F&oq=site&aqs=chrome.0.69i59j69i57j46j0l2j69i60l2j69i61.1067j1j7&sourceid=chrome&ie=UTF-8) you see the cookie text appear quite often

When you [search using something more specific](https://www.google.com/search?ei=pzTzXvSWGsyX8gL3-6WAAg&q=nhs+service+manual+accessibility&oq=nhs+service+manual+accessibility&gs_lcp=CgZwc3ktYWIQAzIECAAQHjoECAAQRzoECAAQDToGCAAQBxAeOggIABAIEAcQHjoGCAAQDRAeOggIABAIEA0QHlCGngFYkqsBYPasAWgAcAJ4AIABgwGIAeAJkgEEMTQuMZgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwi0hr-xqJrqAhXMi1wKHfd9CSAQ4dUDCAw&uact=5) you see the description appear as expected.

**Comment by AdamChrimes** [comment]
This is also happening on our NHS website coronavirus testing pages (which have a meta description)

<img width="917" alt="Screenshot 2020-06-25 at 11 39 11" src="https://user-images.githubusercontent.com/11615501/85704756-7fb54a00-b6d8-11ea-8b39-ff5e54e9f941.png">
